### ISSUE TITLE
Implement checking for the secret

### ISSUE THREAD

**Issue by pinpox** [binaryplease/gitea-matrix-bot#2]
The bot right now doesn't care for the secret. It should only do something if the secret is correct

**Comment by turt2live** [comment]
one way to do this in a multi-user environment is to require the Matrix user to interact with the bot first. For example, the process could be:
1. Open a private chat with `@bot:example.org`
2. Say `!gitea secret #myroom:example.org`
3. *Bot returns a secret with the `/post` URL*
4. *User sets up gitea accordingly*

**Comment by pinpox** [comment]
I will be implementing this. Also I'm thinking about ditching the !subscribe and !unsubscribe commands and leaving this to the settings of the post hook. The user could just use the given `/post` URL in whatever repos he wants (more then one are possible with the same secret) and wouldn't have to subscribe to anything.
